# Generated by Django 5.1.2 on 2024-10-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение пользователя', null=True, upload_to='users/', verbose_name='Изображение'),
        ),
    ]
