# Generated by Django 5.1.2 on 2024-10-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailscaner', '0001_initial'),
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emails',
            field=models.ManyToManyField(help_text='Эмеилы принадлежащие пользователю', related_name='users', to='mailscaner.email', verbose_name='эмеилы'),
        ),
    ]
