# Generated by Django 5.1.2 on 2024-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailscaner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='password',
            field=models.CharField(help_text='Пароль от почты', max_length=254, verbose_name='password'),
        ),
    ]
