# Generated by Django 5.1.2 on 2024-10-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailscaner', '0002_alter_email_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='last_index',
            field=models.BinaryField(blank=True, help_text='Последний uid выгруженного из почты', null=True, verbose_name='последний индекс'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.EmailField(blank=True, help_text='Отправитель письма', max_length=254, null=True, verbose_name='отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, help_text='Тема сообщения', max_length=254, null=True, verbose_name='тема'),
        ),
    ]
