# Generated by Django 5.1.2 on 2024-10-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailscaner', '0004_file_remove_message_file_message_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, help_text='Текст из сообщения', null=True, verbose_name='текст сообщения'),
        ),
    ]
