# Generated by Django 5.1.2 on 2024-10-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailscaner', '0005_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, help_text='Файл из сообщения, если есть', max_length=200, null=True, upload_to='images/', verbose_name='файл'),
        ),
    ]
