# Generated by Django 5.1.2 on 2024-10-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailscaner', '0006_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, help_text='Файл из сообщения, если есть', max_length=300, null=True, upload_to='images/', verbose_name='файл'),
        ),
    ]
