# Generated by Django 5.1.2 on 2024-10-29 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailscaner', '0007_alter_file_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('user_id', 'address'), name='unique_user_address_constraint'),
        ),
    ]
