# Generated by Django 5.1.2 on 2024-10-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailscaner', '0008_email_unique_user_address_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
